name: bauhouse
description: Bauhouse application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.3.1
  equatable: ^2.0.5
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_launcher_icons: ^0.11.0
  # flutter_native_splash: ^2.2.17
  go_router: ^6.0.3
  hooks_riverpod: ^2.1.3
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 22
