name: bauhouse
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.3.1
  equatable: ^2.0.5
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_native_splash: ^2.2.17
  go_router: ^6.0.2
  hooks_riverpod: ^2.1.3
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/image.png

flutter_native_splash:
  color: "#000000"
